### ISSUE TITLE
thread 'main' panicked at src/objects/user.rs:341:36

### ISSUE THREAD

**Issue by Acebond** [g0h4n/RustHound-CE#2]
![image](https://github.com/user-attachments/assets/7433f778-c86c-4d21-8ede-79eebd7b0662)
I was trying RustHound and it crashed and with the error below:
```
Parsing LDAP objects: 0%
thread 'main' panicked at src/objects/user.rs:341:36:
called Option::unwrap() on a None value
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by g0h4n** [comment]
Hi @Acebond,

I think I fixed the issue with commit https://github.com/g0h4n/RustHound-CE/commit/68d2ba77f432eeddcec6c198a8d099aefccf0b96
